import { Translations } from "./types";

export const TRANSLATIONS: Translations = {
  appTitle: { en: "PrintShop Hub", ar: "مركز خدمات الطباعة" },
  uploadTitle: { en: "Upload Your Documents", ar: "ارفع ملفاتك للطباعة" },
  uploadSub: {
    en: "Quick, easy, and secure document printing.",
    ar: "طباعة مستندات سريعة وسهلة وآمنة.",
  },
  customerName: { en: "Customer Name", ar: "اسم العميل" },
  phoneNumber: { en: "Phone Number", ar: "رقم الهاتف" },
  notes: {
    en: "Notes (e.g. Number of copies, color/BW)",
    ar: "ملاحظات (مثلاً: عدد النسخ، ملون/أبيض وأسود)",
  },
  selectFile: { en: "Select File", ar: "اختر ملفاً" },
  uploadBtn: { en: "Upload and Submit", ar: "رفع وإرسال" },
  adminLogin: { en: "Admin Login", ar: "دخول المسؤول" },
  password: { en: "Password", ar: "كلمة المرور" },
  loginBtn: { en: "Login", ar: "تسجيل الدخول" },
  dashboard: { en: "Admin Dashboard", ar: "لوحة التحكم" },
  logout: { en: "Logout", ar: "خروج" },
  noJobs: { en: "No print jobs found.", ar: "لا توجد طلبات طباعة." },
  fileName: { en: "File Name", ar: "اسم الملف" },
  status: { en: "Status", ar: "الحالة" },
  date: { en: "Date", ar: "التاريخ" },
  actions: { en: "Actions", ar: "الإجراءات" },
  pending: { en: "Pending", ar: "قيد الانتظار" },
  ready: { en: "Ready", ar: "جاهز للاستلام" },
  printed: { en: "Printed", ar: "تمت الطباعة" },
  download: { en: "Download", ar: "تحميل" },
  delete: { en: "Delete", ar: "حذف" },
  successMsg: { en: "File uploaded successfully!", ar: "تم رفع الملف بنجاح!" },
  errorMsg: {
    en: "Something went wrong. Please try again.",
    ar: "حدث خطأ ما. يرجى المحاولة مرة أخرى.",
  },
  dragDrop: {
    en: "Drag and drop or click to upload",
    ar: "اسحب وأفلت أو انقر للرفع",
  },
  fileLimit: {
    en: "Supported: PDF, DOCX, Excel, PPT, Image",
    ar: "المدعومة: PDF, Word, Excel, PowerPoint, صور",
  },
  settings: { en: "Settings", ar: "الإعدادات" },
  shopName: { en: "Shop Name", ar: "اسم المحل" },
  shopLogo: { en: "Shop Logo", ar: "شعار المحل" },
  saveSettings: { en: "Save Settings", ar: "حفظ الإعدادات" },
  jobs: { en: "Print Jobs", ar: "طلبات الطباعة" },
  edit: { en: "Edit/Crop", ar: "تعديل/قص" },
  print: { en: "Print", ar: "طباعة" },
  save: { en: "Save Changes", ar: "حفظ التغييرات" },
  cancel: { en: "Cancel", ar: "إلغاء" },
  normalCrop: { en: "Normal Crop", ar: "قص عادي" },
  perspectiveCut: { en: "Perspective Cut", ar: "قص منظوري" },
  recentUploads: { en: "My Recent Uploads", ar: "ملفاتي المرفوعة مؤخراً" },
  paperType: { en: "Paper Type", ar: "نوع الورق" },
  normalPaper: { en: "Normal", ar: "عادي" },
  glossyPaper: { en: "Glossy", ar: "لامع" },
  cardboardPaper: { en: "Cardboard", ar: "ورق مقوى" },
  // Print Studio
  studioTitle: { en: "Print Studio", ar: "استوديو الطباعة" },
  cardsTab: { en: "Cards & IDs", ar: "بطاقات وبطاقات تعريف" },
  pdfTab: { en: "PDF Jobs", ar: "ملفات PDF" },
  frontImage: { en: "Front Image", ar: "الصورة الأمامية" },
  backImage: { en: "Back Image", ar: "الصورة الخلفية" },
  uploadFront: { en: "Upload front image", ar: "رفع الصورة الأمامية" },
  uploadBack: { en: "Upload back image", ar: "رفع الصورة الخلفية" },
  loadFromJobs: { en: "Load from Jobs", ar: "تحميل من الطلبات" },
  remove: { en: "Remove", ar: "إزالة" },
  multipleCards: { en: "Multiple cards per page", ar: "بطاقات متعددة في الصفحة" },
  columns: { en: "Columns", ar: "الأعمدة" },
  rows: { en: "Rows", ar: "الصفوف" },
  hGap: { en: "H. Gap (mm)", ar: "الفجوة الأفقية (مم)" },
  vGap: { en: "V. Gap (mm)", ar: "الفجوة الرأسية (مم)" },
  margin: { en: "Margin (mm)", ar: "الهامش (مم)" },
  cardSize: { en: "Card Size", ar: "حجم البطاقة" },
  paperSize: { en: "Paper Size", ar: "حجم الورق" },
  page1Left: { en: "Page 1: left · Page 2: right · same Y position", ar: "صفحة 1: يسار · صفحة 2: يمين · نفس الموضع الرأسي" },
  printDuplex: { en: "Print duplex, flip on long edge for alignment.", ar: "طباعة على الوجهين، قلب على الحافة الطويلة للمحاذاة." },
  addToJobs: { en: "Add to Jobs", ar: "إضافة للطلبات" },
  addToJobsTitle: { en: "Add to Print Jobs", ar: "إضافة لطلبات الطباعة" },
  customerNameRequired: { en: "Customer name *", ar: "اسم العميل *" },
  phone: { en: "Phone", ar: "الهاتف" },
  studioCancel: { en: "Cancel", ar: "إلغاء" },
  addJob: { en: "Add Job", ar: "إضافة طلب" },
  uploading: { en: "Uploading...", ar: "جارٍ الرفع..." },
  exporting: { en: "Exporting...", ar: "جارٍ التصدير..." },
  studioNotes: { en: "Notes", ar: "ملاحظات" },
  // PDF Job Manager
  sourcePDF: { en: "Source PDF", ar: "الملف PDF" },
  uploadPDF: { en: "Upload PDF file", ar: "رفع ملف PDF" },
  loadFromPrintJobs: { en: "Load from Print Jobs", ar: "تحميل من طلبات الطباعة" },
  printOptions: { en: "Print Options", ar: "خيارات الطباعة" },
  copies: { en: "Copies", ar: "عدد النسخ" },
  colorMode: { en: "Color Mode", ar: "وضع الألوان" },
  color: { en: "Color", ar: "ملون" },
  bw: { en: "Black & White", ar: "أبيض وأسود" },
  duplex: { en: "Duplex (double-sided)", ar: "طباعة على الوجهين" },
  splitPDF: { en: "Split PDF", ar: "تقسيم PDF" },
  splitHint: { en: "Enter page ranges (e.g. 1-5, 6-10)", ar: "أدخل نطاقات الصفحات (مثال: 1-5, 6-10)" },
  split: { en: "Split", ar: "تقسيم" },
  fromPage: { en: "From", ar: "من" },
  toPage: { en: "To", ar: "إلى" },
  splitByRange: { en: "Split by Range", ar: "تقسيم حسب النطاق" },
  pages: { en: "Pages", ar: "الصفحات" },
  exportReady: { en: "Export Print-Ready PDF", ar: "تصدير PDF جاهز للطباعة" },
  exportSplit: { en: "Export Split PDFs", ar: "تصدير أقسام PDF" },
  noImages: { en: "Upload front and back images", ar: "ارفع الصور الأمامية والخلفية" },
  page1: { en: "Page 1 (Front)", ar: "صفحة 1 (أمامي)" },
  page2: { en: "Page 2 (Back)", ar: "صفحة 2 (خلفي)" },
  preview: { en: "Preview", ar: "معاينة" },
  noImage: { en: "No image", ar: "لا توجد صورة" },
  uploadPDFPrompt: { en: "Upload a PDF to see its pages", ar: "ارفع ملف PDF لعرض الصفحات" },
  up: { en: "Up", ar: "أعلى" },
  down: { en: "Down", ar: "أسفل" },
};

export const ALLOWED_TYPES = [
  "application/pdf",
  "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  "application/vnd.ms-excel",
  "application/vnd.openxmlformats-officedocument.presentationml.presentation",
  "application/vnd.ms-powerpoint",
  "image/jpeg",
  "image/png",
];
